name: Release
on: create

jobs:
  build:
    if: github.ref_type == 'tag'
    uses: preactjs/preact/.github/workflows/ci.yml@master

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: npm-package
      - name: Create draft release
        id: create-release
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./scripts/release/create-gh-release.cjs')
            return script({ github, context })
      - name: Upload release artifact
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./scripts/release/upload-gh-asset.cjs')
            return script({ require, github, context, glob, release: ${{ steps.create-release.outputs.result }} })
